export PATH="/u/home/z/zzh237/EPIC/.pixi/envs/default/bin:/u/home/z/zzh237/.cargo/bin:/u/home/z/zzh237/.pixi/bin:/u/home/z/zzh237/anaconda3/bin:/u/local/compilers/intel/2020.4/compilers_and_libraries_2020.4.304/linux/bin/intel64:/u/local/compilers/intel/2020.4/compilers_and_libraries_2020.4.304/linux/bin:/u/local/compilers/intel/2020.4/compilers_and_libraries_2020.4.304/linux/mpi/intel64/libfabric/bin:/u/local/compilers/intel/2020.4/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin:/u/local/compilers/intel/2020.4/debugger_2020/gdb/intel64/bin:/u/systems/UGE8.6.4/bin/lx-amd64:/u/local/bin:/u/local/sbin:/u/local/Modules/4.7.0/gcc-4.8.5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/u/home/z/zzh237/bin:/u/home/z/zzh237/.local/share/JetBrains/Toolbox/scripts"
export CONDA_PREFIX="/u/home/z/zzh237/EPIC/.pixi/envs/default"
export PIXI_EXE="/u/home/z/zzh237/.pixi/bin/pixi"
export PIXI_PROJECT_MANIFEST="/u/home/z/zzh237/EPIC/pyproject.toml"
export PIXI_IN_SHELL="1"
export PIXI_PROJECT_ROOT="/u/home/z/zzh237/EPIC"
export PIXI_PROJECT_VERSION="0.1.0"
export PIXI_PROJECT_NAME="epic"
export CONDA_DEFAULT_ENV="epic"
export PIXI_ENVIRONMENT_NAME="default"
export PIXI_ENVIRONMENT_PLATFORMS="osx-arm64,linux-64"
export PIXI_PROMPT="(epic) "
. "/u/home/z/zzh237/EPIC/.pixi/envs/default/etc/conda/activate.d/libglib_activate.sh"
. "/u/home/z/zzh237/EPIC/.pixi/envs/default/etc/conda/activate.d/libxml2_activate.sh"

