name: epic
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - box2d-py
  - higher
  - cudatoolkit=11.0
  - pytorch::pytorch=1.7.1
  - cython=0.29.36
  - pip
  - pip:
    - mlflow
    - gym==0.18.0
    - wandb
variables:
  CC: gcc-12