[project]
authors = []
dependencies = ["gym==0.22.0", "mlflow>=2.15.1,<3", "wandb>=0.17.6,<0.18", "mujoco-py>=2.1.2.14,<3", "cython>=0.29.6,<0.30.0"]
description = "epic PAC bound for lifetime learning"
name = "epic"
requires-python = "~= 3.8.0"
version = "0.1.0"

[build-system]
# build-backend = "setuptools"
# requires = ["setuptools==65.5.0"]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64"]

[tool.pixi.system-requirements]
libc = {family = "glibc", version = "2.27" }
cuda = "11"

[tool.pixi.pypi-dependencies]
epic = { path = ".", editable = true }
# "setuptools==65.5.0", "pip==21"
# setuptools = "=65.5.0"

[tool.pixi.tasks]

[tool.pixi.target.linux-64.dependencies]
# pytorch = "1.7.1.
box2d-py = ">=2.3.8,<3"
higher = ">=0.2.1,<0.3"
cudatoolkit = "11.0.*"

[tool.pixi.dependencies]
pytorch = "1.7.1.*"

# these might be available in the environment in qsub, in which case it's better to not 
# install another copy
# [tool.pixi.dependencies]
# gcc = "~=12.0"
# patchelf = ">=0.17.2,<0.18"
# mesalib = ">=24.1.5,<25"
