defaults:
# load root "config.yaml" from libero configs
  - config

seed: 90099

benchmark_name: libero_10

policy:
  policy_type: MyTransformerPolicy

lifelong:
  algo: MyLifelongAlgo

train:
  n_epochs: 1

eval:
  num_procs: 1
  n_eval: 5

hydra:
  searchpath:
    - pkg://libero.configs


dev_mode: False