name: Docker Image CI

on:
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ckchow/epic:latest
