name: Docker Image CI

on:
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/ckchow/epic
    - name: Push image
      run: docker push ghcr.io/ckchow/epic
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
